### ISSUE TITLE
vagrant things

### ISSUE THREAD

**Issue by markwellis** [catshop/catshop#10]
the bashrc it creates is wrong. it should _append_ the perlbrew thing to .bash_profile, rather than blaping .bashrc

also is there a way to make it add my public ssh key so i can ssh in, as i won't always want to run vagrant ssh, as more often than not i have a lot of terminals open

and is there a way to have a puppet_local, so i can tell it to copy my .vim file, install things like vim etc and so on?

**Comment by markwellis** [comment]
also httpd wasn't enabled and started

**Comment by grim8634** [comment]
httpd is started, I've rebuilt it twice on different machines today and both times it was. You can't append to a file using puppet very easily because it would do it _every_ time you ran provision. I'll have  a think about it.

**Comment by grim8634** [comment]
Look at pull request https://github.com/catshop/catshop/pull/13 for your local config, ssh key stuff.

**Comment by markwellis** [comment]
merged
